// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using ShtikLive.Shows.Data;
using System;

namespace ShtikLive.Shows.Migrate.Migrations
{
    [DbContext(typeof(ShowContext))]
    [Migration("20170819224325_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.0.0-rtm-26452");

            modelBuilder.Entity("ShtikLive.Shows.Data.Show", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Place")
                        .HasMaxLength(256);

                    b.Property<string>("Slug")
                        .HasMaxLength(256);

                    b.Property<DateTimeOffset>("Time");

                    b.Property<string>("Title")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.ToTable("Shows");
                });

            modelBuilder.Entity("ShtikLive.Shows.Data.Slide", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Html");

                    b.Property<int>("Index");

                    b.Property<string>("Layout")
                        .HasMaxLength(256);

                    b.Property<int>("ShowId");

                    b.Property<string>("Title")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("ShowId");

                    b.ToTable("Slides");
                });

            modelBuilder.Entity("ShtikLive.Shows.Data.Slide", b =>
                {
                    b.HasOne("ShtikLive.Shows.Data.Show")
                        .WithMany("Slides")
                        .HasForeignKey("ShowId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
